### ISSUE TITLE
Return message from input_data function

### ISSUE THREAD

**Issue by ghost** [GEOS-ESM/evagram_input#5]
Return an informative message to the user after running input_data.  How many plots were inserted?  Can we provide a basic summary of those plots?  Consider construction/storing the message in the session class as an attribute along with any information needed for that message.

**Comment by brandonzhu09** [comment]
Is it possible that we can use log files to store the messages returned by running `input_data`? I feel like since `input_data` wraps the Session object it would be hard to access the message as an attribute of the session class.

**Comment by asewnath** [comment]
Don't worry about creating a log for right now

Stuff to print:
- Sucessful input_data run for owner, experiment
- number of diagnostics inserted into database
